CREATE TABLE `ORDERS`(
`ORD_NO` int NOT NULL,
`USER_NO` int NOT NULL,
`ORD_TIME` datetime NOT NULL,
`ORD_NAME` varchar(20) NOT NULL DEFAULT '',
`TAKE_NAME` varchar(20) NOT NULL DEFAULT '',
`TAKE_MAIL` varchar(20) NOT NULL DEFAULT '',
`TAKE_TEL` varchar(10) NOT NULL DEFAULT '',
`TAKE_ADDRESS` varchar(100) NOT NULL DEFAULT '',
`ORD_SHIPPING` tinyint NOT NULL DEFAULT '1',
`PAYMENT_STATUS` tinyint NOT NULL DEFAULT '1',
`ORD_STATUS` tinyint NOT NULL DEFAULT '1',
`DELIVERY_FEE` int,
`ORD_AMOUNT` int NOT NULL,
`SALES_AMOUNT` int,
`ORD_PAYMENT` int NOT NULL,
`USER_SALES` DECIMAL (3,2),
PRIMARY KEY (`ORD_NO`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `ORDERS`(`ORD_NO`,`USER_NO`,`ORD_TIME`,`ORD_NAME`,`TAKE_NAME`,`TAKE_MAIL`,`TAKE_TEL`,`TAKE_ADDRESS`,
`ORD_SHIPPING`,`PAYMENT_STATUS`,`ORD_STATUS`,`DELIVERY_FEE`,`ORD_AMOUNT`,`SALES_AMOUNT`,`ORD_PAYMENT`,`USER_SALES`)VALUES
(231231182410,1,'2023-12-31 18:24:10','王小名','王小名','aabbcc@test.com',0988123456,'桃園市中壢區成功路88號',1,1,1,60,3000,
10,2745,0.9);

CREATE TABLE `ORDER_DETAILS`(
`ORD_DETAILS_NO` int NOT NULL,
`ORD_NO` int NOT NULL,
`PRODUCT_NO` int NOT NULL,
`PRODUCT_NAME` varchar(20) NOT NULL DEFAULT '',
`PURCHASE_COUNT` int NOT NULL,
`PURCHASE_PRICE` int NOT NULL,
PRIMARY KEY (`ORD_DETAILS_NO`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `ORDER_DETAILS`(
`ORD_DETAILS_NO`,`ORD_NO`,`PRODUCT_NO`,`PRODUCT_NAME`,`PURCHASE_COUNT`,`PURCHASE_PRICE`)VALUES
(1,231231182410,1001,'南瓜蔬食調理包',1,330);

create table `FAVORITE`(
`FAVORITE_NO`int NOT NULL,
`USER_NO`int NOT NULL,
`PRODUCT_NO`int NOT NULL,
`PRODUCT_NAME`varchar(20) NOT NULL DEFAULT '',
PRIMARY KEY (`FAVORITE_NO`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into `FAVORITE`(
`FAVORITE_NO`,`USER_NO`,`PRODUCT_NO`,`PRODUCT_NAME`)VALUES
(1,1,1001,'南瓜蔬食調理包');

create table `FEATURED_PRODUCT`(
`FEATURED_PRODUCT_NO`int NOT NULL,
`PRODUCT_NO`int NOT NULL,
PRIMARY KEY (`FEATURED_PRODUCT_NO`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into `FEATURED_PRODUCT`(
`FEATURED_PRODUCT_NO`,`PRODUCT_NO`)VALUES
(1,1001);
